// Generated by Wrangler by running `wrangler types`

interface Env {
	RESULTS_KV: KVNamespace;
	API_KEYS: KVNamespace;
	UPGRADE_URL: "https://aznp.pages.dev/pricing";
	SERVICE_WALLET_ADDRESS: "GuUdPHj3dnafbFvF2gMscCVAMCd4NvSE5ktsrbdAvT4E";
	SOLANA_RPC_URL: "https://api.mainnet-beta.solana.com";
	USDC_MINT_ADDRESS: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
	X402_PRICE_USDC: "0.00166";
	X402_NETWORK: "solana";
	DB: D1Database;
}
